#define PA0_INPUT (DDRA=DDRA &~(1<<0))
#define PA1_INPUT (DDRA=DDRA &~(1<<1))
#define PA2_INPUT (DDRA=DDRA &~(1<<2))
#define PA3_INPUT (DDRA=DDRA &~(1<<3))
#define PA4_INPUT (DDRA=DDRA &~(1<<4))
#define PA5_INPUT (DDRA=DDRA &~(1<<5))
#define PA6_INPUT (DDRA=DDRA &~(1<<6))
#define PA7_INPUT (DDRA=DDRA &~(1<<7))

#define PC0_OUTPUT (DDRC=DDRC|(1<<0))
#define PC1_OUTPUT (DDRC=DDRC|(1<<1))
#define PC2_OUTPUT (DDRC=DDRC|(1<<2))
#define PC3_OUTPUT (DDRC=DDRC|(1<<3))
#define PC4_OUTPUT (DDRC=DDRC|(1<<4))
#define PC5_OUTPUT (DDRC=DDRC|(1<<5))
#define PC6_OUTPUT (DDRC=DDRC|(1<<6))
#define PC7_OUTPUT (DDRC=DDRC|(1<<7))


#define SW0 (PINA&(1<<0))
#define SW1 (PINA&(1<<1))
#define SW2 (PINA&(1<<2))
#define SW3 (PINA&(1<<3))
#define SW4 (PINA&(1<<4))
#define SW5 (PINA&(1<<5))
#define SW6 (PINA&(1<<6))
#define SW7 (PINA&(1<<7))

#define LED0_ON (PORTC=PORTC|(1<<0))
#define LED1_ON (PORTC=PORTC|(1<<1))
#define LED2_ON (PORTC=PORTC|(1<<2))
#define LED3_ON (PORTC=PORTC|(1<<3))
#define LED4_ON (PORTC=PORTC|(1<<4))
#define LED5_ON (PORTC=PORTC|(1<<5))
#define LED6_ON (PORTC=PORTC|(1<<6))
#define LED7_ON (PORTC=PORTC|(1<<7))

#define LED0_OFF (PORTC=PORTC&~(1<<0))
#define LED1_OFF (PORTC=PORTC&~(1<<1))
#define LED2_OFF (PORTC=PORTC&~(1<<2))
#define LED3_OFF (PORTC=PORTC&~(1<<3))
#define LED4_OFF (PORTC=PORTC&~(1<<4))
#define LED5_OFF (PORTC=PORTC&~(1<<5))
#define LED6_OFF (PORTC=PORTC&~(1<<6))
#define LED7_OFF (PORTC=PORTC&~(1<<7))
